import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Reveal } from "@/components/Reveal";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://jobybots.com";

export const metadata: Metadata = {
  title: "Dashboard guide · How JobyBots tracks every job, email and reply",
  description:
    "Your JobyBots dashboard is a single HTML file generated by the bot, refreshed every 15 seconds while running. It shows jobs found, emails sent, bounce rate, recruiter replies and an hourly chart — all opened from a double-click. No login, no SaaS, no server keeps a copy.",
  alternates: { canonical: `${SITE_URL}/dashboard-guide` },
  openGraph: {
    title: "JobyBots Dashboard guide — local, live, beautiful",
    description:
      "Every metric you need on one screen, generated locally from your own data.",
    url: `${SITE_URL}/dashboard-guide`,
    type: "article",
    images: [
      {
        url: `${SITE_URL}/install-storyboard/install-09-dashboard.png`,
        width: 1024,
        height: 683,
        alt: "JobyBots live dashboard",
      },
    ],
  },
};

const METRICS = [
  { label: "Jobs found",       desc: "Across LinkedIn, Bayt, Naukrigulf, GulfTalent, Indeed, RemoteOK and 40+ company career pages." },
  { label: "AI-scored",        desc: "Gemini ranks each job against your résumé. Anything below your match threshold (default 60) is dropped." },
  { label: "Emails sent",      desc: "Personalised cover letters sent through your Gmail SMTP, capped at your daily limit." },
  { label: "Bounces",          desc: "Tracked in real-time via IMAP. Every bad address is quarantined so you don't burn your sender reputation." },
  { label: "Recruiter replies",desc: "Anything that lands in your inbox after JobyBots emailed someone. The whole point of the product." },
  { label: "Today vs yesterday",desc: "Hourly bar chart so you can spot when the right batch goes out." },
];

const FILES = [
  {
    name: "data/dashboard.html",
    role: "The main dashboard",
    body: "A single self-contained HTML file with inline CSS + a tiny JS bundle. Auto-refreshes every 15 seconds while a cycle is running. Open it any time with DASHBOARD.bat (Windows) or mac/Dashboard.command (Mac).",
  },
  {
    name: "data/click_apply_inbox.html",
    role: "LinkedIn Easy Apply queue",
    body: "Companies that only accept LinkedIn applications (no public email) appear here. Click each card → opens the LinkedIn job → click 'Easy Apply'. JobyBots auto-fills nothing — you stay in control.",
  },
  {
    name: "data/jobybot.db",
    role: "SQLite tracker",
    body: "Every job already considered, scored, applied or skipped. Open with any SQLite browser (free) if you want to slice it yourself.",
  },
  {
    name: "data/jobybot_launchd.log (Mac) or scheduler logs (Windows)",
    role: "Run history",
    body: "Plain text logs of every cycle. View live with `tail -f` (Mac) or just open in Notepad.",
  },
];

export default function DashboardGuidePage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-cream via-white to-white">
      {/* HERO */}
      <section className="mx-auto max-w-4xl px-6 pt-20 pb-12">
        <Reveal>
          <p className="text-xs font-semibold uppercase tracking-[0.22em] text-accent-strong">
            Dashboard guide · Live · Local
          </p>
        </Reveal>
        <Reveal delay={1}>
          <h1 className="mt-3 text-3xl sm:text-5xl font-bold text-ink tracking-tight">
            One HTML file. Every metric. Refreshes every 15 seconds.
          </h1>
        </Reveal>
        <Reveal delay={2}>
          <p className="mt-6 text-lg text-slate-700 leading-relaxed">
            JobyBots doesn't have a "cloud dashboard" you log in to — because
            we don't run a cloud. Instead, every cycle the bot writes a
            self-contained <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">data/dashboard.html</code>{" "}
            file with inline CSS and a small JavaScript helper. Double-click it
            to open in your browser. <strong>It looks like a SaaS dashboard
            because it's the SaaS dashboard you would have built — except it
            lives in a folder on your laptop, not on someone else's server.</strong>
          </p>
        </Reveal>
        <Reveal delay={3}>
          <div className="mt-6 inline-flex flex-wrap gap-2 text-xs">
            <Link
              href="/dashboard"
              className="rounded-full border border-slate-300 px-3 py-1.5 text-slate-700 transition hover:bg-slate-50"
            >
              See the live preview →
            </Link>
            <Link
              href="/security"
              className="rounded-full border border-slate-300 px-3 py-1.5 text-slate-700 transition hover:bg-slate-50"
            >
              Why is this safe?
            </Link>
          </div>
        </Reveal>
      </section>

      {/* SCREENSHOT */}
      <section className="mx-auto max-w-5xl px-6 pb-16">
        <Reveal>
          <div className="rounded-3xl overflow-hidden ring-1 ring-slate-200/70 shadow-2xl shadow-slate-900/10">
            <Image
              src="/install-storyboard/install-09-dashboard.png"
              alt="JobyBots live dashboard showing 47 jobs found, 38 emails sent, 0 bounces, 6 recruiter replies and an hourly chart"
              width={1024}
              height={683}
              priority
              sizes="(min-width: 1024px) 1024px, 100vw"
              className="w-full h-auto"
            />
          </div>
        </Reveal>
      </section>

      {/* METRICS */}
      <section className="mx-auto max-w-5xl px-6 pb-16">
        <Reveal>
          <h2 className="text-2xl sm:text-3xl font-bold text-ink">
            What you'll see at a glance
          </h2>
        </Reveal>
        <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {METRICS.map((m, i) => (
            <Reveal
              key={m.label}
              delay={Math.min(6, (i + 1)) as 1 | 2 | 3 | 4 | 5 | 6}
              className="rounded-2xl border border-slate-200 bg-white p-5"
            >
              <p className="font-display text-base font-semibold text-ink">
                {m.label}
              </p>
              <p className="mt-2 text-sm leading-relaxed text-slate-700">
                {m.desc}
              </p>
            </Reveal>
          ))}
        </div>
      </section>

      {/* HOW TO OPEN */}
      <section className="bg-ink text-white">
        <div className="mx-auto max-w-4xl px-6 py-16">
          <Reveal>
            <h2 className="text-2xl sm:text-3xl font-bold">
              How to open the dashboard
            </h2>
          </Reveal>
          <div className="mt-8 grid gap-6 md:grid-cols-2">
            <Reveal
              delay={1}
              className="rounded-2xl border border-white/10 bg-white/5 p-6"
            >
              <p className="font-mono text-xs uppercase tracking-[0.18em] text-accent">
                Windows
              </p>
              <p className="mt-2 font-display text-lg font-semibold">
                Double-click <code>DASHBOARD.bat</code>
              </p>
              <p className="mt-3 text-sm leading-relaxed text-white/85">
                Or open <code>data/dashboard.html</code> directly in any
                browser. Or pin it to the Edge / Chrome bookmarks bar so
                it's always one click away.
              </p>
            </Reveal>
            <Reveal
              delay={2}
              className="rounded-2xl border border-white/10 bg-white/5 p-6"
            >
              <p className="font-mono text-xs uppercase tracking-[0.18em] text-accent">
                macOS
              </p>
              <p className="mt-2 font-display text-lg font-semibold">
                Double-click <code>mac/Dashboard.command</code>
              </p>
              <p className="mt-3 text-sm leading-relaxed text-white/85">
                Or open <code>data/dashboard.html</code> directly in Safari /
                Chrome / Firefox. Drag the file to your Dock for one-click
                access.
              </p>
            </Reveal>
          </div>

          <Reveal delay={3}>
            <p className="mt-10 text-sm text-white/75 leading-relaxed">
              Want to share the dashboard with a friend or coach? Right-click
              <code> data/dashboard.html </code>→ <strong>Send to →
              Compressed folder</strong> (Windows) or zip it on Mac, and email
              the ZIP. Because the file is self-contained (inline CSS, no
              external requests), it opens in any browser anywhere.{" "}
              <strong>You decide who sees it.</strong>
            </p>
          </Reveal>
        </div>
      </section>

      {/* FILE INVENTORY */}
      <section className="mx-auto max-w-5xl px-6 py-16">
        <Reveal>
          <h2 className="text-2xl sm:text-3xl font-bold text-ink">
            Every tracker file, in one place
          </h2>
        </Reveal>
        <div className="mt-8 grid gap-4 md:grid-cols-2">
          {FILES.map((f, i) => (
            <Reveal
              key={f.name}
              delay={Math.min(4, (i + 1)) as 1 | 2 | 3 | 4}
              className="rounded-2xl border border-slate-200 bg-white p-5"
            >
              <p className="font-mono text-xs font-bold text-accent-strong">
                {f.role}
              </p>
              <p className="mt-1.5 font-mono text-[13px] font-semibold text-ink">
                {f.name}
              </p>
              <p className="mt-2 text-[13px] leading-relaxed text-slate-700">
                {f.body}
              </p>
            </Reveal>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-3xl px-6 pb-24">
        <Reveal>
          <div className="rounded-3xl bg-gradient-to-br from-accent to-accent-strong p-10 text-white shadow-2xl">
            <p className="text-sm font-semibold uppercase tracking-widest opacity-80">
              The shape of the product
            </p>
            <h2 className="mt-3 text-3xl font-bold tracking-tight">
              You buy a tool. You configure it once. You watch a dashboard.
            </h2>
            <p className="mt-4 text-base leading-relaxed opacity-95">
              That's the whole UX. No subscription nags, no login screens, no
              "upgrade for analytics", no email reminders. JobyBots earns its
              ₹2,999 once and shuts up forever.
            </p>
            <div className="mt-7 flex flex-wrap gap-4">
              <Link
                href="/setup"
                className="rounded-full bg-white px-6 py-3 text-sm font-semibold text-accent-strong hover:bg-cream transition"
              >
                Build my .env in the browser →
              </Link>
              <Link
                href="/install"
                className="rounded-full border border-white/70 px-6 py-3 text-sm font-semibold text-white hover:bg-white/10 transition"
              >
                See the install steps
              </Link>
            </div>
          </div>
        </Reveal>
      </section>
    </main>
  );
}
